'use strict';

exports.fakeUsersInfo = [ {
  "name" : "User PEPE",
  "email" : "pepe@organization.com",
  "userid" : "u1",
  "avatar" : "http://avatarURL",
  "scmuserurl" : "http://scmavatarURL",
  "register" : 1306360800000,
  "lastcommit" : 1432591200000,
  "firstcommit": 1306360800000,
  "skype" : "http://skypeURL",
  "linkedin" : "http://linkedinURL",
  "twitter" : "http://twitterURL",
  "website" : "http://websiteURL",
},
{
  "name" : "User LOLA",
  "email" : "lola@organization.com",
  "userid" : "u2",
  "avatar" : "http://avatarURL",
  "scmuserurl" : "http://scmavatarURL",
  "register" : 1306360800000,
  "lastcommit" : 1432591200000,
  "firstcommit": 1306360800000,
  "skype" : "http://skypeURL",
  "linkedin" : "http://linkedinURL",
  "twitter" : "http://twitterURL",
  "website" : "http://websiteURL",
},
{
  "name" : "User JORDI",
  "email" : "jordi@organization.com",
  "userid" : "u3",
  "avatar" : "http://avatarURL",
  "scmuserurl" : "http://scmavatarURL",
  "register" : 1306360800000,
  "lastcommit" : 1432591200000,
  "firstcommit": 1306360800000,
  "skype" : "http://skypeURL",
  "linkedin" : "http://linkedinURL",
  "twitter" : "http://twitterURL",
  "website" : "http://websiteURL",
} ];